curl -L --data "name=TheHandsomeFamily01&artist=FarFromAnyRoad" localhost:3001/songs/new
curl -L --data "name=TheHandsomeFamily02&artist=FarFromAnyRoad" localhost:3001/songs/new
curl -L --data "name=TheHandsomeFamily03&artist=FarFromAnyRoad" localhost:3001/songs/new
curl -L --data "name=TheHandsomeFamily04&artist=FarFromAnyRoad" localhost:3001/songs/new
curl -L --data "name=TheHandsomeFamily05&artist=FarFromAnyRoad" localhost:3001/songs/new
curl -L --data "name=TheHandsomeFamily06&artist=FarFromAnyRoad" localhost:3001/songs/new
curl -L --data "name=TheHandsomeFamily07&artist=FarFromAnyRoad" localhost:3001/songs/new
curl -L --data "name=TheHandsomeFamily08&artist=FarFromAnyRoad" localhost:3001/songs/new
curl -L --data "name=TheHandsomeFamily09&artist=FarFromAnyRoad" localhost:3001/songs/new
curl -L --data "name=TheHandsomeFamily10&artist=FarFromAnyRoad" localhost:3001/songs/new
curl -L --data "name=TheHandsomeFamily11&artist=FarFromAnyRoad" localhost:3001/songs/new
